### ISSUE TITLE
Add third-party client that supports hysteria protocol

### ISSUE THREAD

**Issue by hezhaozhao-git** [apernet/hysteria-website#19]
https://github.com/fagao-ai/kitty
这个项目是支持hysteria的客户端，希望可以进入推荐列表，目前支持windows，linux，macos

**Comment by haruue** [comment]
您好。

很高兴能看到新的第三方客户端支持 Hysteria。

不过这个项目似乎还处于相当早期的开发阶段， 甚至还没有一个完善的 README 来介绍它（注意到 https://github.com/fagao-ai/kitty/issues/2 ）。

我尝试在 Windows 上安装 [kitty_0.0.3_x64_en-US.msi](https://github.com/fagao-ai/kitty/releases/download/kitty_0.0.3/kitty_0.0.3_x64_en-US.msi) 进行测试， 但是这个版本似乎还有诸多问题， 例如添加节点之后无法更新（显示下图的报错）， 也没有「移除」按钮。 

![Screenshot_20240526_204409](https://github.com/apernet/hysteria-website/assets/13131972/cedd1464-867a-4ae5-b133-3e2380af5224)

**Comment by haruue** [comment]
您好， 由于未能收到回复， 我现在关闭此 Issue。 
欢迎在项目完善之后重新打开它， 您也可以直接向这个仓库提交 PR 进行修改。

Hysteria 网站上的「第三方应用」列表， 位于这两个文件
英文： https://github.com/apernet/hysteria-website/blob/master/docs/docs/getting-started/3rd-party-apps.md
中文： https://github.com/apernet/hysteria-website/blob/master/docs/docs/getting-started/3rd-party-apps.zh.md
