### ISSUE TITLE
TProxy nftables rule clarification

### ISSUE THREAD

**Issue by unidcml** [apernet/hysteria-website#35]
The [documentation](https://v2.hysteria.network/docs/advanced/TPROXY/#__tabbed_2_3) suggests using the nftables rule
```
socket transparent 0 counter return
```
It looks like this rule is preventing new connections from being established to TProxy. I suggest using this rule instead
```
ct state != new socket transparent 0 counter return
```

**Comment by haruue** [comment]
Thank you for the suggestion!

Would you please create a Pull Request for it?

You can find the source of the TPROXY docs [here](https://github.com/apernet/hysteria-website/blob/a0c0921a41294b8147a97c599f065349fb1d794f/docs/docs/advanced/TPROXY.md?plain=1#L198).
