### ISSUE TITLE
URI Scheme：需要解释清楚 auth@ 的 auth 需要 percent encoding

### ISSUE THREAD

**Issue by ze0lite** [apernet/hysteria-website#39]
请见2dust/v2rayN#5807

> 不要填写不支持的字符串就好了，hy2协议开发者那边定义的密码属性是没有转义的，所以就不支持保留字符。
如果你是在备注属性填就没事，因为这个属性会被转义

_Originally posted by @2dust in https://github.com/2dust/v2rayN/issues/5807#issuecomment-2406581019_
            

> 好，https://v2.hysteria.network/zh/docs/developers/URI-Scheme/ 确实没写清，但是按照 https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1 `userinfo`  的格式，确实应该接受 pct-encoded 和 unreserved 而不该接受 "/"

_Originally posted by @ze0lite in https://github.com/2dust/v2rayN/issues/5807#issuecomment-2409417294_

**Comment by tobyxdd** [comment]
感谢反馈，文档已经添加相关部分
