### ISSUE TITLE
Typo in "About-HTTP3.md"

### ISSUE THREAD

**Issue by Maoyeedy** [apernet/hysteria-website#4]
[docs/docs/misc/About-HTTP3.md](https://github.com/apernet/hysteria-website/blob/master/docs/docs/misc/About-HTTP3.md)
> Firefox: Go to `about:config`, find `network.http.http3.enabled` and toggle it to `false`.

[docs/docs/misc/About-HTTP3.zh.md](https://github.com/apernet/hysteria-website/blob/master/docs/docs/misc/About-HTTP3.zh.md)
> Firefox: 打开 `about:config` 找到 `network.http.http3.enabled` 选项，切换到 `false`

### Fix
Should be `network.http.http3.enable` instead of `network.http.http3.enabled`.

<img src="https://github.com/apernet/hysteria-website/assets/100255436/ba9e6433-57ea-423c-821e-a74e06751688" width="50%">

**Comment by tobyxdd** [comment]
Fixed
